wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/src/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648057867
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
dataset_kwargs:
  desc: null
  value:
    batch_size: 128
    num_workers: 4
    val_batch_size: 128
exp_name:
  desc: null
  value: test
module_kwargs:
  desc: null
  value:
    optim: '{''optimizer'': ''sgd'', ''scheduler'': ''step'', ''lr'': 0.01, ''momentum'':
      0.5, ''step_size'': 10, ''weight_decay'': None, ''gamma'': 0.1}'
project:
  desc: null
  value: mnist_training_test
save_dir:
  desc: null
  value: ./outputs
trainer_kwargs:
  desc: null
  value:
    epochs: 30
    gpus:
    - 0
    - 1
    ip: 127.0.0.1
    log_interval: 10
    port: '29500'
    resume: false
    resume_path: null
    save_interval: false
    seed: 1
