name: test

batch_sampler_type: default
accum_grad: False
num_workers: 4
epochs: 30
log_interval: 10
save_interval: 3
gpus: [0,1]
# gpus: [0]
seq:
  train:
    - MOT17-02
    - MOT17-04
    - MOT17-05
    - MOT17-10
    - MOT17-11
    - MOT17-13
  val:
    - MOT17-09
model:
  backbone:
    freeze: False
    trainable_backbone_layers: 3

  detector:
    freeze: False
    model: faster_rcnn

  tracker:
    # freeze: False
    freeze: False
    loss: bce
    model: lstm
    input_size: 256
    num_layers: 2
train:
  batch_size: 128
  optim:
    optimizer: sgd
    scheduler: step
    lr: 0.01
    momentum: 0.5
    step_size: 10
    weight_decay: 
    gamma: 0.1
val:
  batch_size: 128